name: Cornica
version: '0.3-SNAPSHOT'
main: org.example.cornica.cornica.Cornica
api-version: '1.21'
authors: [ ShortPupper14484 ]
description: cornica is a plugin inteaded for a friends minecraft server
